[2022-07-28 07:36:14,558] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-07-28T07:36:13.674361+00:00 [queued]>
[2022-07-28 07:36:14,568] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-07-28T07:36:13.674361+00:00 [queued]>
[2022-07-28 07:36:14,569] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 07:36:14,569] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-28 07:36:14,570] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-28 07:36:14,590] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): also_run_this> on 2022-07-28 07:36:13.674361+00:00
[2022-07-28 07:36:14,595] {standard_task_runner.py:52} INFO - Started process 1424 to run task
[2022-07-28 07:36:14,599] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'manual__2022-07-28T07:36:13.674361+00:00', '--job-id', '14', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmp93emo_vr', '--error-file', '/tmp/tmp5ig6fk6s']
[2022-07-28 07:36:14,600] {standard_task_runner.py:80} INFO - Job 14: Subtask also_run_this
[2022-07-28 07:36:14,665] {task_command.py:369} INFO - Running <TaskInstance: example_bash_operator.also_run_this manual__2022-07-28T07:36:13.674361+00:00 [running]> on host 084bc8ac965b
[2022-07-28 07:36:14,749] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-07-28T07:36:13.674361+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-28T07:36:13.674361+00:00
[2022-07-28 07:36:14,750] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-28 07:36:14,751] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=manual__2022-07-28T07:36:13.674361+00:00 | dag_run=<DagRun example_bash_operator @ 2022-07-28 07:36:13.674361+00:00: manual__2022-07-28T07:36:13.674361+00:00, externally triggered: True>"']
[2022-07-28 07:36:14,760] {subprocess.py:85} INFO - Output:
[2022-07-28 07:36:14,762] {subprocess.py:92} INFO - run_id=manual__2022-07-28T07:36:13.674361+00:00 | dag_run=<DagRun example_bash_operator @ 2022-07-28 07:36:13.674361+00:00: manual__2022-07-28T07:36:13.674361+00:00, externally triggered: True>
[2022-07-28 07:36:14,762] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-28 07:36:14,794] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20220728T073613, start_date=20220728T073614, end_date=20220728T073614
[2022-07-28 07:36:14,813] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-28 07:36:14,848] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
